import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from "@mantine/core";
import { Manrope } from "next/font/google";
import ThemeProvider from "@/components/providers/ThemeProvider";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps} className={manrope.variable}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className="font-sans antialiased">
        <ThemeProvider>
          <MantineProvider>{children}</MantineProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
